// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApv3a95FxGEefb3RZQyijjxtqiux1hG_4',
    appId: '1:417337246003:web:3b6bcfc253544f4c2ebe46',
    messagingSenderId: '417337246003',
    projectId: 'maps-fa651',
    authDomain: 'maps-fa651.firebaseapp.com',
    storageBucket: 'maps-fa651.appspot.com',
    measurementId: 'G-RJMDJBESCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1HD0YGKqnQRW0qRoAkLfEgXXkdV13qM',
    appId: '1:417337246003:android:94bfb54df22ba8bd2ebe46',
    messagingSenderId: '417337246003',
    projectId: 'maps-fa651',
    storageBucket: 'maps-fa651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60TW3wp-aGYxGEgxc0V5tDTD8eVTlw7s',
    appId: '1:417337246003:ios:cc1b43b5fb37ab502ebe46',
    messagingSenderId: '417337246003',
    projectId: 'maps-fa651',
    storageBucket: 'maps-fa651.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB60TW3wp-aGYxGEgxc0V5tDTD8eVTlw7s',
    appId: '1:417337246003:ios:cc1b43b5fb37ab502ebe46',
    messagingSenderId: '417337246003',
    projectId: 'maps-fa651',
    storageBucket: 'maps-fa651.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApv3a95FxGEefb3RZQyijjxtqiux1hG_4',
    appId: '1:417337246003:web:d70a6135f48f83082ebe46',
    messagingSenderId: '417337246003',
    projectId: 'maps-fa651',
    authDomain: 'maps-fa651.firebaseapp.com',
    storageBucket: 'maps-fa651.appspot.com',
    measurementId: 'G-QQK8EPEGHB',
  );
}
